### ISSUE TITLE
Import Beerxml 

### ISSUE THREAD

**Issue by jawsdaws** [matthewkris/mibrew-issues#55]
I was trying to import a recipe, but xml import had some errors in the background.  I had to zoom in to get the sidebar out of the way to see them.  I'm fairly sure this is caused by my input file so there may not be anything to do here unless you want to try to support everything that could possibly be an input.

![Screenshot from 2019-03-09 10-11-04](https://user-images.githubusercontent.com/3501812/54073357-3a0b0e80-4254-11e9-86a6-3187070e52d0.png)

**Comment by matthewkris** [comment]
Fixed on 2019-03-11
