### ISSUE TITLE
Editing yeast quantity in inventory seems to just delete everything.

### ISSUE THREAD

**Issue by jawsdaws** [matthewkris/mibrew-issues#58]
Title basically.  Seems to reproduce every time.

**Comment by matthewkris** [comment]
Fixed and will be pushed to production shortly! Will update this when it's live.

**Comment by matthewkris** [comment]
Side note, if you edited a yeast it was actually moving it into a Fermentable item. Once this is live you may want to double check your fermentable inventory.

**Comment by matthewkris** [comment]
Pushed to prod.

**Comment by jawsdaws** [comment]
Just edited my inventory.  There were some strange things in fermentables, but some quick cleanup seems to have done the trick.  Yeast seems to work. Thank you!
