### ISSUE TITLE
Defaults and settings not saving

### ISSUE THREAD

**Issue by hnnrrk** [matthewkris/mibrew-issues#63]
When editing a few items on my [profile settings page](https://www.mibrewsupply.com/recipe/settings), some fields and sections are not saving, including
* Account Info/Profile: Location, photo
* Recipe and Equipment Defaults

The message shows up after saving but the inputs set does not show correctly in the form:
> Success! Settings have been saved.

Water Profile Default, however does save successfully.

**Comment by Conan-86** [comment]
Same Issue.
In addition, changes in the unit or the equation method are not saved as well despite the success message appearing.
As reported by hnnrrk, the water profile however is saved.
Tried on linux with firefox and chromium browsers

**Comment by matthewkris** [comment]
This issue has been resolved. It was due to an issue with saving the avatar/profile picture, which then caused the other fields to not update.

Sorry for the delay on this - we are FINALLY getting back to working on regular updates to the software.
