### ISSUE TITLE
BeerXML Import Not Working

### ISSUE THREAD

**Issue by captainkrunchz** [matthewkris/mibrew-issues#65]
The beerxml import fails with an invalid path message to my client's xml.  I tried both Windows and Mac OS, Safari and Chrome and same result.  I cannot manually alter the path information after selecting the file on my client.

**Comment by matthewkris** [comment]
Thanks for reporting the issue. Could you attach the file you are trying to import here?

**Comment by captainkrunchz** [comment]
[HopslamClone.xml.zip](https://github.com/matthewkris/mibrew-issues/files/6304419/HopslamClone.xml.zip)

**Comment by matthewkris** [comment]
The path issue has been resolved and you can upload the xml file now. Thanks agains!

**Comment by captainkrunchz** [comment]
Hey Matt.  Import XML did indeed process the XML so I could see it formatted in my browser, but on submit browser timed out.  Can’t get back to the website now.  Did site go down?

——
***@***.***

**Comment by captainkrunchz** [comment]
disregard previous note.  no longer seeing site timeout error.  was able to import my xml.  thanks.  

——
***@***.***
