### ISSUE TITLE
Profile picture update isn't updating.

### ISSUE THREAD

**Issue by jawsdaws** [matthewkris/mibrew-issues#67]
Hey Matt. Hope all is well.  Was just trying to update the profile picture for 3 Bridges and I only get this error.  
![Screenshot from 2022-10-12 09-25-55](https://user-images.githubusercontent.com/3501812/195355133-d7ff8cd1-68a7-461c-93a4-7bd46ac25230.png)

**Comment by matthewkris** [comment]
This has FINALLY been resolved.
